LetsGo/LetsGo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static, serve
from django.conf import settings

from LetsGo.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),

    # Example : /
    # Homepage URL
    url(r'^$', HomeView.as_view(), name='home'),

    # Example : /result
    url(r'^result/', include('analy.urls', namespace='analy')),

] + static(settings.MEDIA_URL, document_url=settings.MEDIA_ROOT)

LetsGo/analy/urls.py
from django.conf.urls import url
from analy.views import *


urlpatterns = [
    # Example : /result/user_id
    url(r'^(?P<pk>\d+)$', UserDV.as_view(), name='index'),

    # Example : /result/user_id/picture_list
    url(r'^(?P<pk>\d+)/picture_list', PictureDV.as_view(), name='picture_list'),

    # Exmaple : /result/another_user
    url(r'^another_user', UserLV.as_view(), name='another_user'),

    # Example : /result/another_user/user_id
    url(r'^another_user/(?P<pk>\d+)', AnotherUserDV.as_view(), name='another'),

    # Example : /result/data/photo_id
    url(r'^data/(?P<pk>)\d+', get_exif_json),

    # Example : /result/data/photo/photo_id
    url(r'^data/photo/(?P<pk>)\d+', get_photo_json),
]

LetsGo/analy/models.py
from django.db import models
from django.core.urlresolvers import reverse

from analy.fields import MyImageField

import pdb
# Create your models here.

"""
model 정리

1. User
    user id
    user name

2. Picture
    user id
    picture id
    picture name
    picture image (field)

3. Exif
    picture id
    exif ...
"""

class User(models.Model):
    name = models.CharField("Nick Name", max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('analy:another', args=(self.id, ))


class Photo(models.Model):

    def file_path(instance, filename):

        return '/'.join(filter(None, (str(instance.user_id), filename)))

    user = models.ForeignKey(User)
    title = models.CharField("Title", max_length=100)
    image = MyImageField(upload_to=file_path)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def dic(self):
        fields = [
            'id', 'title', 'user_id'
        ]
        result = {}

        for field in fields:
            result[field] = self.__dict__[field]

        return result


class Exif(models.Model):
    photo = models.ForeignKey(Photo)
    make = models.CharField("Manufacturer", max_length=50)
    camera_model = models.CharField("Model", max_length=50)
    date_time = models.CharField("Date Time", max_length=50)
    iso_speed = models.CharField("ISO Speed", max_length=50)
    color = models.CharField("Color Space", max_length=50)
    latitude = models.CharField("Latitude", max_length=50)
    longitude = models.CharField("Longitude", max_length=50)
    orientation = models.CharField("Direction of Rotation", max_length=50)
    focal_length = models.CharField("Focus Length", max_length=50)
    flash = models.CharField("Flash", max_length=50)

    class Meta:
        db_table = 'Exif_info'
        ordering = ('-date_time', )


    def __str__(self):
        return self.make + "/" + self.latitude + '/' + self.longitude

    def dic(self):
        fields = [
            'make', 'camera_model', 'date_time', 'iso_speed', 'color',
            'latitude', 'longitude', 'orientation', 'focal_length', 'flash', 'id'
        ]

        result = {}

        for field in fields:
            result[field] = self.__dict__[field]

        return result

LetsGo/analy/forms.py
from django import forms
from django.views.generic.edit import FormView

# --- form 설정

class PhotoForm(forms.Form):
    user = forms.CharField(max_length=50)
    image = forms.ImageField()

class SearchUserForm(forms.Form):
    search_word = forms.CharField(label="Search User")

LetsGo/analy/views.py
from django.views.generic import ListView, DetailView
from analy.models import User, Photo
from analy.forms import SearchUserForm
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger

from django.db.models import Q
from django.shortcuts import render, HttpResponse
import json
from django.core.urlresolvers import reverse
import pdb
# Create your views here.


class UserDV(DetailView):
    model = User
    template_name = 'analy/analy_result.html'


class PictureDV(DetailView):
    model = User
    template_name = 'analy/analy_picture_list.html'

    def get_context_data(self, **kwargs):
        context = super(PictureDV, self).get_context_data(**kwargs)
        photo_list = context['object'].photo_set.all()
        paginator = Paginator(photo_list, 12)

        page = self.request.GET.get('page')

        try:
            photo_data = paginator.page(page)
        except PageNotAnInteger:
            photo_data = paginator.page(1)
        except EmptyPage:
            photo_data = paginator.page(paginator.num_pages)

        context['photo_data'] = photo_data
        return context


class UserLV(ListView):
    model = User
    template_name = 'analy/analy_another_user.html'

    def post(self, request, *args, **kwargs):
        form = SearchUserForm(request.POST)
        search_user = '%s' % request.POST['search_word']

        user_list = User.objects.filter(Q(name__icontains=search_user)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = search_user
        context['my_list'] = user_list

        return render(request, self.template_name, context)

    def get(self, request, *args, **kwargs):
        flag = request.path.split('/')[-1]

        if flag == 'another_user':
            return super(UserLV, self).get(request, args, kwargs)
        else:
            context = {}
            context['object'] = User.objects.filter(id=flag).first()
            photo_list = context['object'].photo_set.all()
            paginator = Paginator(photo_list, 12)
            page = self.request.GET.get('page')

            try:
                photo_data = paginator.page(page)
            except PageNotAnInteger:
                photo_data = paginator.page(1)
            except EmptyPage:
                photo_data = paginator.page(paginator.num_pages)

            context['photo_data'] = photo_data

            return render(request, 'analy/another_user_list.html', context)


class AnotherUserDV(DetailView):
    model = User
    template_name = 'analy/another_user_list.html'


# GET JSON 필요

def get_exif_json(request, pk):
    """ /json/data/photo_id """
    user_id = request.path.split('/')[-1]
    user_data = User.objects.filter(id=user_id).first()
    photo_data = user_data.photo_set.all()
    data = []
    for photo in photo_data:
        exif_data = photo.exif_set.all().first().dic()
        data.append(exif_data)

    return HttpResponse(json.dumps(data), content_type='application/json')


def get_photo_json(request, pk):
    photo_id = request.path.split('/')[-1]
    photo_data = Photo.objects.filter(id=photo_id).first()
    data = photo_data.dic()

    return HttpResponse(json.dumps(data), content_type='application/json')

LetsGo/analy/templates/analy/analy_another_user.html
{% extends 'analy/list_view_base.html' %}

{% block title %} Search User {% endblock %}

{% block content %}{% load staticfiles %}
    <div class="container">
        <div class="row">
            <div class="col-md-12"><br/>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"> Search User</h3>
                    </div>
                    <div class="panel-body"><br/>
                        <form action="{% url 'analy:another_user' %}" method="post">{% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" name="search_word"/>
                                <span class="input-group-btn">
                                    <input type="submit" value="Search" class="btn btn-info"/>
                                </span>
                            </div>
                        </form>
                        <br/>
                        {% if my_list %}
                        {% for usr in my_list %}
                        <h2><a href="{{ usr.get_absolute_url }}">{{ usr }}</a></h2>
                        {% endfor %}
                        {% elif search_term %}
                        <b><i>Not Found! Search Word: {{ search_term }}</i></b>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

LetsGo/analy/templates/analy/analy_other_user.html
{% extends 'analy/base.html' %}

{% block title %} analy_other_list {% endblock %}

{% block content %}{% load staticfiles %}


    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Other User</p>
                <div class="list-group">
                    <a href="#" class="list-group-item active">Other User1</a>
                    <a href="#" class="list-group-item">Other User2</a>
                    <a href="#" class="list-group-item">Other User4</a>
                    <a href="#" class="list-group-item">Other User5</a>
                    <a href="#" class="list-group-item">Other User6</a>
                    <a href="#" class="list-group-item">Other User7</a>
                    <a href="#" class="list-group-item">Other User8</a>
                    <a href="#" class="list-group-item">Other User9</a>
                    <a href="#" class="list-group-item">Other User10</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="thumbnail">
                    <img class="img-responsive" src="{% static 'analy/vendor/img/f.png' %}" alt=""/>
                    <div class="caption-full">
                        <h4><a href="#">Picture</a>
                        </h4>
                        <p>abcdefghijklmnopqrstuvwxyz</p>
                    </div>
                    <div class="col-lg-12">
                        <h3 class="page-header">Other Picture</h3>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="{% static 'analy/vendor/img/b.jpg' %}" alt=""/>
                        </a>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/c.jpg" alt=""/>
                        </a>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/d.jpg" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/e.jpg" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/g.png" alt=""/>
                        </a>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/h.jpg" alt=""/>
                        </a>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/i.jpg" alt=""/>
                        </a>
                    </div>

                    <div class="col-sm-3 col-xs-6">
                        <a href="#">
                            <img class="img-responsive portfolio-item" src="../../static/analy/vendor/img/j.jpg" alt=""/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

LetsGo/analy/templates/analy/analy_picture_list.html
{% extends 'analy/base.html' %}
{% load staticfiles %}
{% block title %} {{ object | upper}}'s Picture {% endblock %}
{% block extra_css %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h1><strong>{{ object|upper }}</strong>  <small>{{ object.photo_set.all.count }} Photos</small></h1>
            </div>
        </div>
        <div class="row">
            {% for photo in photo_data %}
                <div class="col-md-3 portfolio-item">
                    <a href="{{ photo.image.url }}">
                        <img class="img-responsive" src="{{ photo.image.url }}" alt="">
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <ul class="pagination">
                {% if photo_data.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ photo_data.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                {% endif %}
                <li class="page-item">
                    {% for index in photo_data.paginator.page_range %}
                    <a class="page-link" href="?page={{index}}">{{ index }}</a>
                    {% endfor %}
                </li>
                {% if photo_data.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ photo_data.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block extra_js %}

{% endblock %}

LetsGo/analy/templates/analy/analy_result.html
{% extends 'analy/base.html' %}

{% block title %}{{object |upper }}'s result{% endblock %}
{% load staticfiles %}
{% block content %}

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Post Content Column -->
                <div class="page-header">
                    <h1><strong>{{ object | upper }}</strong> <small>{{ object.photo_set.all.count }} Photos</small></h1>
                </div>
        </div>
        <div class="row">
            <!-- Preview Image -->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    MAP
                </div>
                <div class="panel-body">
                    <div id="my_map" class="my_map"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <h1>Time Line</h1>
                </div>
                <div style="display:inline-block;width:100%;overflow-y:auto;">
                    <ul class="timeline timeline-horizontal">
                        {% for photo in object.photo_set.all %}
                        {% if photo.exif_set %}
                        <li class="timeline-item">
                            <div class="timeline-badge success"><i class="glyphicon glyphicon-check"></i></div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="timeline-title">{{ photo.title }}</h4>
                                    <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> {{ photo.exif_set.all.first.date_time }}</small></p>
                                </div>
                                <div class="timeline-body"><p>{{ photo.exif_set.all.first.camera_model }}</p></div>
                            </div>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <h1> Exif Info </h1>
                </div>
                <div id="exif_info">
                    Select Marker
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'analy/js/my_map.js' %}"></script>
{% endblock %}

LetsGo/analy/templates/analy/another_user_list.html
{% extends 'analy/list_view_base.html' %}

{% block title %} another_user_list.html {% endblock %}
{% load staticfiles %}
{% block extra_css %}
<link href="{% static 'analy/css/other_css.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1> {{ object | upper }} </h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                MAP
            </div>
            <div class="panel-body">
                <div id="other_map" class="other_map"></div>
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                Photos
            </div>
            <div class="panel-body">
                <div class="row">
                    {% for photo in photo_data %}
                        <div class="col-md-3 portfolio-item">
                            <img class="img-responsive" src="{{ photo.image.url }}" alt="">
                        </div>
                    {% endfor %}
                </div>
                <div class="row" style="margin-left: 10px;">
                    <ul class="pagination">
                        {% if photo_data.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ photo_data.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        {% endif %}
                        <li class="page-item">
                            {% for index in photo_data.paginator.page_range %}
                            <a class="page-link" href="?page={{index}}">{{ index }}</a>
                            {% endfor %}
                        </li>
                        {% if photo_data.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ photo_data.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'analy/js/other_map.js' %}"></script>
{% endblock %}

LetsGo/analy/templates/analy/base.html
<!Doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Sunmoon Univ{% endblock %}</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'analy/vendor/css/bootstrap.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- Custom CSS -->
    <link href="{% static 'analy/vendor/css/portfolio-item.css' %}" rel="stylesheet">
    <link href="{% static 'analy/css/my_css.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'analy:index' object.id %}">Sunmoon Univ</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'analy:index' object.id %}">Result</a>
                    </li>
                    <li>
                        <a href="{% url 'analy:picture_list' object.id %}">Picture List</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}

    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Department of Computer Engineering, OpensourceProject</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'analy/vendor/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'analy/vendor/js/bootstrap.js' %}"></script>


    <!-- Google Map api -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC2O4P5PYYu0eeKK1rI0K2vpLKXIAxqX3c"></script>

    <!-- Custom JavaScript -->
    {% block extra_js %}{% endblock %}
</body>
</html>

LetsGo/analy/templates/analy/list_view_base.html
<!Doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Sunmoon Univ{% endblock %}</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'analy/vendor/css/bootstrap.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- Custom CSS -->
    <link href="{% static 'analy/vendor/css/portfolio-item.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Sunmoon Univ</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'analy:another_user' %}">Other User</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Department of Computer Engineering, OpensourceProject</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="{% static 'analy/vendor/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'analy/vendor/js/bootstrap.js' %}"></script>

    <!-- Google Map api -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC2O4P5PYYu0eeKK1rI0K2vpLKXIAxqX3c"></script>

    <!-- Custom JavaScript -->
    {% block extra_js %}{% endblock %}
</body>
</html>